### PR TITLE
[speechx] fix copyright issue

### LINKED ISSUE #1839: Add acknowledgment to WeNet
Parts of the `speechx` projects are basically the same as the ones used inside WeNet. I would recommend adding acknowledgment to WeNet in `speechx/README.md`.

1. `websocket_server` and  `websocket_client` are basically equal to WebSocket in WeNet, see `diff` below:
72cb781624f8454f74fa8b4be483165
efabdb41e7d3d57f04465fd06edbfef

2. `openfst patch` is identical to WeNet, it is non-trivial to find proper patches and make them work correctly in the whole WeNet project. This kind of work is time-consuming but could be easily overlooked.

### PR DESCRIPTION
**Pull request by SmileGoat**
### PR types

[bug fixes]
### Describe

fix #1839

### CODE REVIEW

**Review by zh794390558 — APPROVED** [review]
LGTM

**Comment by robin1001** [comment]
I'm the author of WeNet.

The copyright should be
```
// Copyright (c) 2020 Mobvoi Inc (Binbin Zhang)
                          2022 PaddlePaddle Authors
```
if you do some modification. otherwise, it should not be changed.

Everyone should respect the copyright even for open source software.

**Comment by zh794390558** [comment]
Hi @robin1001  ，thanks for the reminder of the copyright issue. We have added the authors and acknowledge in the related code.https://github.com/PaddlePaddle/PaddleSpeech/pull/1849  In those code, we refer the design of the websocket in Wenet, which is compact and useful. With that help, we save lot of time and energy, speeding up the development. We are really grateful about the contributions of Wenet to the opensource software, which help us spend more time and energy on the pressing and valuable issues. Also, We are looking forward to working with Wenet to make more valuable contributions, and make the technology easier and popular.


Acknowledgement for reference repo：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/reference.md

**Comment by robin1001** [comment]
Thanks for the reply and fix.
Looking forward to cowork with the PaddleSpeech team to make more contribution to speech community.

**Pull request merged**
