### PR TITLE
[TTS]fix tone, update readme

### PR DESCRIPTION
**Pull request by yt605155624**

### CODE REVIEW

**Comment by yt605155624** [comment]
@david-95

**Review by david-95 — COMMENTED** [review]
ok

**Comment by yt605155624** [comment]
需等 https://github.com/PaddlePaddle/PaddleSpeech/pull/2334 合入后重新跑 CI

**Comment by yt605155624** [comment]
> Details

done

**Review by lym0302 — APPROVED** [review]

**Pull request merged**
