### PR TITLE
[doc] fix some typos

### PR DESCRIPTION
**Pull request by billishyahao**
### PR types

Bug fixes

### PR changes

Others

### Describe

Fix some typos.

### CODE REVIEW

**Comment by yt605155624** [comment]
please sign for CLA first,
thx

**Comment by yt605155624** [comment]
Have you used some typo check tools to find these errors ？🥺😅

**Comment by billishyahao** [comment]
> please sign for CLA first, thx

Done

**Comment by billishyahao** [comment]
> Have you used some typo check tools to find these errors ？🥺😅

I am studying this repo so find these typos.

**Review by yt605155624 — APPROVED** [review]
LGTM

**Pull request merged**
